.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "QLESS\-POOL\.YML" "5" "May 2012" "QLESS-POOL 0.3.0.DEV" "QLESS-POOL"
.
.SH "NAME"
\fBqless\-pool\.yml\fR \- qless\-pool pool configuration
.
.SH "SYNOPSIS"
\fBqless\-pool\.yml\fR
.
.br
\fBconfig/qless\-pool\.yml\fR
.
.SH "DESCRIPTION"
qless\-pool(1) reads pool configuration data from \fBqless\-pool\.yml\fR (or the file specified with \fB\-c\fR on the command line)\. The file contains queue\-worker\-count pairs, one per line\. The configuration file supports both using root level defaults as well as environment specific overrides (\fBRACK_ENV\fR, \fBRAILS_ENV\fR, and \fBQLESS_ENV\fR environment variables can be used to determine environment)\.
.
.P
An example configuration
.
.IP "" 4
.
.nf

foo: 1
bar: 2
"foo,bar,baz": 1

production:
  "foo,bar,baz": 4
.
.fi
.
.IP "" 0
.
.P
will create 7 workers in production and 4 in other environment configurations\. The simpler worker definition \fBfoo: 1\fR will create 1 worker for the \fBfoo\fR queue, the more complicated \fBfoo,bar,baz: 1\fR will create 1 worker for the queues \fBfoo\fR, \fBbar\fR and \fBbaz\fR\.
.
.SH "AUTHOR"
Nicholas Evans
.
.SH "COPYRIGHT"
Copyright (C) 2010 by Nicholas Evans \fInick@ekenosen\.net\fR, et al\.
.
.SH "SEE ALSO"
qless\-pool(1)
