# If you have redis running on the standard port on localhost, then you can
# test out qless-pool in the examples directory by running:
#
#    rake --trace qless:pool
#
# And then you can poke and prod the various processes with signals and edit
# the config file, etc.
require 'qless/pool/tasks'
